CREATE TABLE Locations(
  IDLoc INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  FKUser INT(10) UNSIGNED NOT NULL,
  FKSnow INT(11) NOT NULL,
  DateLoc DATE,
  QtyLoc SMALLINT,
  NbDLoc SMALLINT,
  PRIMARY KEY (`IDLoc`),
  FOREIGN KEY (FKUser) REFERENCES users(IDUser),
  FOREIGN KEY (FKSnow) REFERENCES snows(IDSnow)
) COLLATE = 'utf8_general_ci' ENGINE = InnoDB;

