ALTER TABLE Users CHANGE id userID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE snows CHANGE id snowID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE users ADD COLUMN userType INT(2) NOT NULL DEFAULT '1' AFTER userHashPsw;